# Generated by Django 4.2.3 on 2023-07-30 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must contain at least 8 characters.', regex='^.{8,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must contain at least 8 characters.', regex='^.{8,}$')]),
        ),
    ]
