# Generated by Django 4.2.3 on 2024-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_artpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpost',
            name='type',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], default='digital', max_length=20),
            preserve_default=False,
        ),
    ]
