# Generated by Django 4.2.3 on 2024-05-17 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_alter_artpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpost',
            name='type',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('nft', 'NFT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='artpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
