# Generated by Django 4.2.3 on 2024-05-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_artpost_type_alter_artpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics/'),
        ),
    ]
