# Generated by Django 4.2.3 on 2024-05-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('basic_user', 'basic user'), ('pending_seller_approval', 'Pending Seller Approval'), ('seller', 'Seller')], default='basic_user', max_length=23),
            preserve_default=False,
        ),
    ]
