# Generated by Django 4.2.3 on 2024-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='country',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='billing',
            name='credit_number',
            field=models.CharField(default='0000000000000000', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='cvv',
            field=models.CharField(default='123', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='expiry_date',
            field=models.CharField(default='1212', max_length=4),
            preserve_default=False,
        ),
    ]
