# Generated by Django 4.2.3 on 2023-08-06 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_user_options_alter_user_managers_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
