# Generated by Django 4.2.3 on 2024-04-24 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_artpost_user_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
