# Generated by Django 4.2.3 on 2024-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_artpost_price_artpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpost',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('photography', 'Photography'), ('sculpture', 'Sculpture'), ('digital_art', 'Digital Art')], default='Digital Art', max_length=20),
            preserve_default=False,
        ),
    ]
