# Generated by Django 4.2.3 on 2024-05-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.artpost'),
            preserve_default=False,
        ),
    ]
