# Generated by Django 4.2.3 on 2024-05-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_subscriberlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberlist',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='subscriberlist',
            name='user',
        ),
    ]
