# Generated by Django 4.2.3 on 2024-05-24 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_remove_subscriberlist_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
