# Generated by Django 4.2.3 on 2024-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_subscriberlist_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='welcome to My profile fellas', max_length=300),
            preserve_default=False,
        ),
    ]
