# Generated by Django 4.2.3 on 2024-05-24 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Joe Mama', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must contain at least 8 characters.', regex='^.{8,}$')]),
        ),
    ]
