# Generated by Django 4.2.3 on 2024-05-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='algeria blida oued-djer', max_length=25),
            preserve_default=False,
        ),
    ]
